### ISSUE TITLE
#1 Use this Tripletnet as pretrained network for binary classification

### ISSUE THREAD

**Issue by azadehashouri** [keshik6/deep-image-retrieval#3]
How can I use this Triplet as pretrain network for binary classification?
I really need your help. Please answer my question. Thanks a lot.

**Comment by keshik6** [comment]
I do not exactly understand your problem statement. But if you want to use the embeddings extracted from the pretrained network to perform binary classification it is possible. i.e. : You basically use the embeddings as features for your classification model (SVM / Decision trees/ neural networks etc).

Hope this helps.
